decentraland/creator-hub

- .github/workflows/ci.yml
- .github/workflows/release.yml
- electron-builder.yml
- package.json
This PR makes the CI sign the MacOS releases and builds them for both arc64 and x64 architectures.
> feat: sign releases

- packages/main/src/modules/cli.ts
- packages/renderer/src/components/Editor/component.tsx
- packages/renderer/src/components/Modals/PublishProject/component.tsx
- packages/renderer/src/hooks/useEditor.ts
- packages/renderer/src/hooks/useWorkspace.ts
- packages/renderer/src/modules/store/editor/slice.ts
- packages/renderer/src/modules/store/index.ts
* fix create scene bug not starting inspector
* add custom server link for 'learn more'
* move npm install to start cli command
> Fix several bugs

- .github/workflows/release.yml
- electron-builder.yml
- package.json
- packages/main/src/index.ts
- packages/main/src/mainWindow.ts
- packages/main/tests/unit.spec.ts
Enable the auto updater by setting the MODE=production. Added more logging and maximize the window automatically as requested.
> feat: auto updater

- packages/preload/src/modules/constants.ts
- packages/preload/src/modules/workspace.ts
> fix: use empty scene template

- packages/main/src/modules/bin.ts
Fix regex for npm install success
> fix: regexp

- packages/renderer/src/components/Editor/component.tsx
- packages/renderer/src/hooks/useEditor.ts
- packages/renderer/src/hooks/useScene.ts
- packages/renderer/src/modules/rpc/camera.ts
- packages/renderer/src/modules/rpc/index.ts
- packages/renderer/src/modules/rpc/storage.ts
- packages/renderer/src/modules/rpc/ui.ts
> feat: ui rpc

- packages/preload/src/modules/workspace.ts
- packages/renderer/src/components/Modals/DeleteProject/component.tsx
- packages/renderer/src/modules/store/translation/locales/en.json
- packages/renderer/src/modules/store/translation/locales/es.json
- packages/renderer/src/modules/store/translation/locales/zh.json
- packages/shared/types/projects.ts
> feat: unlist projects from workspace without deleting the scene

- packages/main/src/modules/cli.ts
- packages/renderer/src/hooks/useEditor.ts
- packages/renderer/src/modules/store/editor/slice.ts
- packages/shared/types/ipc.ts
This PR enables the preview using E@
> feat: preview with explorer alpha

- .github/workflows/ci.yml
- .github/workflows/release.yml
> feat: sign windows exe

- .github/workflows/release.yml
- README.md
- electron-builder.cjs
- package-lock.json
- package.json
- packages/renderer/index.html
- packages/renderer/src/components/Navbar/component.tsx
- packages/renderer/src/modules/store/translation/locales/en.json
- packages/renderer/src/modules/store/translation/locales/es.json
Rename app from `Creators Hub` into `Decentraland Creator Hub` 
Rename `@dcl/creators-hub` into `creator-hub`
> feat: rename app

- packages/renderer/src/hooks/useScene.ts
- packages/renderer/src/modules/rpc/index.ts
- packages/renderer/src/modules/store/editor/slice.ts
- packages/renderer/src/modules/store/ens/slice.ts
- packages/renderer/src/modules/store/ens/types.ts
This PR fixes the deploy world flow because of the missing thumbnail.
Also, it fixes the fetching DCL names method to show them properly.
> fix: Deploy Worlds

- packages/renderer/src/components/HomePage/component.tsx
This PR updates the default tab to `Home`
> fix: Default tab home

- packages/renderer/src/components/ProjectCard/component.tsx
Remove sounds from videos in templates
> fix: remove sound from videos in templates

- packages/renderer/src/components/EditorPage/component.tsx
This PR fixes the deploy to land flow
> fix: PublishScene doesn't updated the project reference

- package-lock.json
- package.json
- packages/main/src/modules/analytics.ts
- packages/main/src/modules/cli.ts
- packages/main/src/modules/electron.ts
- packages/main/src/modules/ipc.ts
- packages/preload/src/modules/analytics.ts
- packages/preload/src/modules/editor.ts
- packages/preload/src/modules/workspace.ts
- packages/shared/types/ipc.ts
This PR integrates the env vars from this PR on the CLI: https://github.com/decentraland/js-sdk-toolchain/pull/1023
> chore: add tracking for CLI relatd to creator hub

- .github/workflows/lint.yml
- package-lock.json
- package.json
This PR upgrades the package: `sdk` to version `7.6.5`
> feat: Upgrade sdk package to version 7.6.5

- README.md
- package-lock.json
This PR is to trigger the release flow
> fix: Bump release

- package-lock.json
- package.json
> feat: upgrade sdk to v7.6.6

- packages/renderer/src/modules/rpc/index.ts
- packages/shared/paths.ts
Instead of `/creators-hub/Custom/custom/some-item` now it's `/creators-hub/Custom Items/some-item`
> fix: make custom items path prettier

- README.md
> chore: adds ADRs to readme

- packages/main/src/modules/cli.ts
This PR makes the editor try to run an npm install if the sdk-commands start fails, only once. This will fix the problem when node_modules has not been installed properly.
> fix: run npm install if cli start fails

- packages/main/src/modules/migrations.ts
moved `await FileSystemStorage.getOrCreate(CONFIG_PATH);` to the top so we ensure the `../Settings/` directory is created before attempting any migration
> fix 'Settings' directory not being created on scenes migration

- package-lock.json
- package.json
[Rename deployment steps](https://github.com/decentraland/creator-hub/issues/412)
[Deployment notifications ](https://github.com/decentraland/creator-hub/issues/413)
[Inspector Canvas: Left and Right Mouse buttons conflicts](https://github.com/decentraland/creator-hub/issues/325)
[Start with Scene Settings open](https://github.com/decentraland/creator-hub/issues/320)
[New scene details screen](https://github.com/decentraland/creator-hub/issues/395)
[Refresh local files button](https://github.com/decentraland/creator-hub/issues/406)
Please leave feedback here so all fixes are done also here and we keep track of them
> [QA] Editor more QoL improvements - Cycle 11

- package-lock.json
- package.json
This PR fixes the Animation's initial weight state. 
When adding a model with animations to the scene, the weight of the Animation starts with a value of `-100`
How to test this PR:
1. Open / Create a Scene
2. Add a model with animations
3. Look at the right side panel for the `Animator` component
- ![image](https://github.com/user-attachments/assets/f347b08e-1268-47d0-ba8a-37ff3da0dfac)
4. Verify the `weight` field is between `0` and `100` 
Fixes: https://github.com/decentraland/creator-hub/issues/473
Depends on: https://github.com/decentraland/js-sdk-toolchain/pull/1090
> fix: Animation's weight

- package-lock.json
- package.json
- packages/main/src/modules/cli.ts
- packages/main/src/modules/ipc.ts
- packages/preload/src/modules/editor.ts
- packages/renderer/src/components/EditorPage/component.tsx
- packages/renderer/src/modules/store/editor/slice.ts
- packages/renderer/src/modules/store/translation/locales/en.json
- packages/renderer/src/modules/store/translation/locales/es.json
- packages/renderer/src/modules/store/translation/locales/zh.json
- packages/renderer/src/modules/store/workspace/slice.ts
- packages/shared/types/config.ts
- packages/shared/types/ipc.ts
- packages/shared/types/settings.ts
depends on: https://github.com/decentraland/js-sdk-toolchain/pull/1096
closes https://github.com/decentraland/creator-hub/issues/513
> add skip-auth-screen & landscape-terrain-enabled options for preview

- package-lock.json
- package.json
https://github.com/decentraland/js-sdk-toolchain/pull/1112
Show the current/selected entity first on the dropdown to select entities.
https://github.com/decentraland/js-sdk-toolchain/pull/1113
- Support search to add action dropdown
- Support search on trigger action and trigger basic view
https://github.com/decentraland/js-sdk-toolchain/pull/1114
- Accept URLs on texture input
> feat: update sdk package

- package-lock.json
- package.json
Release changes:
- Fix an issue on the Audio Source component: global property was not updating
- Allow users to make a sound global when playing a sound on an action
> Update SDK package to release

- package-lock.json
- package.json
ISSUE: https://github.com/decentraland/creator-hub/issues/639
> Fix Play Video not updating src property

- packages/main/src/modules/cli.ts
- packages/shared/dynamic-import.ts
closes https://github.com/decentraland/creator-hub/issues/690
> fix dynamic import

- packages/inspector/src/components/EntityInspector/EntityHeader/EntityHeader.tsx
by @alejandralevy
original: https://github.com/decentraland/js-sdk-toolchain/pull/1207
> feat: remove add component icon on scene, camera and player 

- packages/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.tsx
- packages/inspector/src/components/EntityInspector/NftShapeInspector/NftShapeInspector.tsx
closes https://github.com/decentraland/creator-hub/issues/714
> fix Nft smart item getting removed on select/unselect

- packages/inspector/src/components/AssetPreview/AssetPreview.tsx
This PR is to trigger the release flow again
> fix: Fix eslint
