decentraland/creator-hub

- packages/preload/src/modules/config.ts
- packages/renderer/src/modules/file.ts
- packages/renderer/src/modules/store/index.ts
Avoid using `electron-log` on the renderer because it has an issue where it logs everything twice on the web devtools console
> fix: double logs

- packages/main/src/modules/bin.ts
This PR fixes an issue where the initial installation of the Editor gets stuck.
It's a combination of two issues:
1. The regex that waited for the npm install to finish did no account for "up to date".
2. The version stored in the registry to check if an npm install is needed was wrong (it was the package.json version which is always 0.0.0-dev instead of the app version).
The wrong version caused the Editor to always perform an npm install on start up. So the first time you install the Editor is all good, because the npm install does install packages and the regex matches. The second time you run the Editor, since the version stored was wrong, it will do an npm install again, which goes well, but it print "up to date" instead of "added XXX packages" so the regex keeps waiting forever. …
> fix: stuck update

- packages/main/src/index.ts
- packages/main/src/modules/bin.ts
- packages/main/src/modules/cli.ts
This PR removes the use of the scene path as the workspace when doing a `sdk-commands start` or a `sdk-commands deploy` because when working on scenes that do not have a `node_modules` folder (like [Goerli Plaza](https://github.com/decentraland/sdk7-goerli-plaza), because the `node_modules` is one directory above).
It also removes some warnings from the npm install logs that pollute the main logs.
Closes #57. It does not run commands with `npx` because that did not work properly on the executable version of the app. But this approach still fixes the issue.
> fix: use binaries from editor node_modules in case they are not installed in the scene

- packages/main/src/modules/cli.ts
- packages/renderer/src/hooks/useEditor.ts
- packages/renderer/src/modules/store/editor/slice.ts
- packages/shared/types/ipc.ts
This PR changes the Open Preview feature to open the full URL with params that the `sdk-commands start` usually opens, otherwise it only opens the `http://localhost:XXXX` URL which misses the `position` param, so when the base is not 0,0 you appear far from the scene.
> fix: open preview url with params

- packages/main/src/modules/bin.ts
Add the paths to the bundled binaries (node and npm) at the beggining of the $PATH, so those are used instead of the ones in the system
> fix: path order

- packages/main/src/modules/analytics.ts
- packages/main/src/modules/ipc.ts
- packages/preload/src/modules/analytics.ts
- packages/renderer/src/components/AuthProvider/component.tsx
- packages/renderer/src/modules/store/analytics/slice.ts
- packages/renderer/src/modules/store/analytics/track.ts
- packages/renderer/src/modules/store/analytics/types.ts
- packages/renderer/src/modules/store/analytics/utils.ts
- packages/renderer/src/modules/store/editor/slice.ts
- packages/renderer/src/modules/store/index.ts
- packages/shared/types/ipc.ts
Improved some aspects of analytics as requested:
- Added `project_id` to `PREVIEW` and `PUBLISH` events.
- Switched `userId` for `anonymousId`.
- Added `identify(wallet)` on login. After that, all events will go with `userId` on top of the `anonymousId`.
- Added `target` and `targetContent` to `PUBLISH` to be able to tell if the scene is going to genesis city or a world.
- Added a `sessionId` that lives until the Creator Hub is closed.
> chore: analytics improvements

- packages/preload/src/modules/workspace.ts
- packages/renderer/src/hooks/useEditor.ts
This PR fixes the deployment when the thumbnail doesn't exist, cleaning up the property in the `scene.json` file.
> fix: Validates the navmapThumbnail path

- packages/preload/src/modules/config.ts
Fixes this issue when opening the CH for the first time and the `.decentraland` directory doesn't exist:
> fix: create home path if it doesnt exist when getting config

- packages/renderer/src/components/HomePage/styles.css
- packages/renderer/src/components/LearnPage/styles.css
- packages/renderer/src/components/Navbar/styles.css
Fixes #138 
Before:
After:
Also removes the shadow from the homepage buttons:
Before:
After:
> fix: cosmetic issues

- packages/preload/src/modules/workspace.ts
- packages/renderer/src/modules/store/workspace/slice.ts
Fixes #142
This PR fixes an issue where a duplicated scene could end up with the same name/path as an existing scene. Now it uses the same logic as when creating a new scene to avoid clashing names.
> fix: duplicate scene

- packages/renderer/src/lib/ens.ts
- packages/renderer/src/lib/worlds.ts
- packages/renderer/src/modules/store/ens/slice.ts
- packages/renderer/src/modules/store/ens/types.ts
This PR fetches the contributable worlds for a user.
Closes: https://github.com/decentraland/creator-hub/issues/140
> fix: Fetch Contributable Worlds

- tests/e2e.spec.ts
Sometimes the E2E tests fails because they try to access an element before it is rendered.
This PR fixes this flakyness
> chore: fix e2e tests

- .github/workflows/release.yml
- electron-builder.cjs
Remove the `-{version}` part of the artifacts generated on each release.
This is so we can always point to download the latest version using static links like this: 
```
https://github.com/decentraland/creator-hub/releases/latest/download/Decentraland-Creator-Hub-{os}-{arch}.{ext}
```
- macOS ARM: `https://github.com/decentraland/creator-hub/releases/latest/download/Decentraland-Creator-Hub-mac-arm64.dmg`
- macOS x64: `https://github.com/decentraland/creator-hub/releases/latest/download/Decentraland-Creator-Hub-mac-x64.dmg`
- Windows: `https://github.com/decentraland/creator-hub/releases/latest/download/Decentraland-Creator-Hub-win-x64.exe`
> chore: remove version from artifact

- .github/workflows/release.yml
- electron-builder.cjs
This reverts commit 6a425cf2f5e2ba461c667ae34df7673b944e2c04.
This PR makes the artifacts to include the version again in their filename. This was removed to make the download links static in this PR #237. 
Now the landing fetches the download links from GitHub https://github.com/decentraland/landing/pull/451, so we can add the version back.
This could potentially fix the issues #268 and #284, according to https://github.com/electron-userland/electron-builder/issues/5429#issuecomment-730022611
> Revert "chore: remove version from artifact (#237)"

- packages/renderer/src/modules/rpc/index.ts
This PR modifies the RPC so all the operations that happen within the `custom` directory will be rerouted to the home directory. ie: path `/custom/asset.glb` will be routed to `.decentraland/custom/asset.glb` instead of `/path/to/project/custom/asset.glb`.
This is necessary because we save the custom items under the `/custom` directory, but we don't want that to be saved within each scene, but instead on a shared folder, so when you create a custom asset you will be able to reuse it across projects.
> feat: shared folder for custom assets

- packages/main/src/modules/cli.ts
- packages/renderer/src/components/EditorPage/component.tsx
- packages/renderer/src/modules/store/editor/slice.ts
- packages/renderer/src/modules/store/snackbar/slice.ts
- packages/renderer/src/modules/store/translation/locales/en.json
- packages/renderer/src/modules/store/translation/locales/es.json
- packages/renderer/src/modules/store/translation/locales/zh.json
The Preview & Publish flow was using the creator hub SDK instead of the one inside the scene.
So you CAN'T test other versions of the SDK using the creators-hub
```ts
type RunOptions = {
args?: string[]; // this are the arguments for the command
cwd?: string; // this is the directory where the command should be executed, it defaults to the app path.
env?: Record<string, string>; // this are the env vars that should be added to the command's env
workspace?: string; // this is the path where the node_modules that should be used are located, it defaults to the app path.
};
```
I change the workspace options based on this comment
> use sdk-commands SCENE package

- packages/main/src/index.ts
- packages/main/src/modules/config.ts
- packages/main/src/modules/electron.ts
- packages/main/src/modules/ipc.ts
- packages/main/src/modules/migrations.ts
- packages/preload/src/index.ts
- packages/preload/src/modules/config.ts
- packages/preload/src/modules/custom.ts
- packages/preload/src/modules/settings.ts
- packages/renderer/src/modules/rpc/index.ts
- packages/shared/paths.ts
- packages/shared/types/ipc.ts
This PR changes the default path for scens from `.decentraland` to the electron's `userPath`, and migrates all the imported scenes from that legacy path to the new one.
> feat: use userData path instead of home path

- packages/main/src/modules/handle.ts
- packages/renderer/src/components/AuthProvider/component.tsx
- packages/renderer/src/components/Button/styles.css
- packages/renderer/src/components/EditorPage/component.tsx
- packages/renderer/src/components/Modals/PublishProject/steps/Deploy/component.tsx
- packages/renderer/src/components/Modals/PublishProject/steps/Deploy/styles.css
- packages/renderer/src/components/Modals/PublishProject/steps/Deploy/types.ts
- packages/renderer/src/components/Modals/PublishProject/steps/Deploy/utils.ts
- packages/renderer/src/components/Modals/PublishProject/steps/PublishToLand/component.tsx
- packages/renderer/src/components/Navbar/styles.css
- packages/renderer/src/components/Step/component.tsx
- packages/renderer/src/components/Step/index.ts
- packages/renderer/src/components/Step/styles.css
- packages/renderer/src/components/Step/types.ts
- packages/renderer/src/lib/profile.ts
- packages/renderer/src/modules/store/translation/locales/en.json
- packages/renderer/src/modules/store/translation/locales/es.json
- packages/renderer/src/modules/store/translation/locales/zh.json
- packages/shared/utils.ts
1. Go to `components/Modals/PublishProject/steps/PublishToLand/component.tsx`
* On `void publishScene({ target: ... });` call, change the target to `DEPLOY_URLS.DEV_CATALYST_SERVER`
2. Go to `components/Modals/PublishProject/steps/Deploy/component.tsx`
* On `void deploy({ address: wallet, authChain, chainId })` call, hardcode `chainId: ChainId.ETHEREUM_SEPOLIA`
https://github.com/decentraland/asset-bundle-registry/pull/6
> [DO NOT MERGE] Add deployment status checks

- package-lock.json
- package.json
- packages/main/src/modules/config.ts
- packages/preload/src/modules/config.ts
- packages/shared/paths.ts
- packages/shared/types/config.ts
We discovered a critical issue with config initialization:
1. The analytics module in the main process creates a minimal config file containing only `userId`
2. Later, when the renderer process tries to initialize the config, it skips creating the default config because a config file already exists (even though it's incomplete)
3. This leads to missing critical config properties throughout the application, as the code assumes a complete config structure
This issue was introduced when analytics support was added a few versions back. It specifically affects:
- New installations since that version
- Does NOT affect existing installations that already had a valid config file
- Persists across reinstalls since the config file is stored in the user's app data directory, outside the installation …
> fix: broken new installs

- packages/main/src/modules/analytics.ts
- packages/main/src/modules/config.ts
- packages/main/src/modules/migrations.ts
- packages/preload/src/modules/workspace.ts
- packages/shared/types/config.ts
- packages/shared/types/storage.ts
The config was being reset to default values on app restart because we were incorrectly using `storage.get('')` to check for config existence. This was unreliable and caused the config to reset even when valid data existed.
- Added `getAll()` and `setAll()` methods to read/write entire config state at once
- Properly merge existing config with defaults
- Write back merged config only when necessary
- Added better logging for debugging
Added synchronization to prevent race conditions between config operations and migrations:
- Created `waitForMigrations()` utility using `fp-future`
- Modified `getConfig()` to await migrations before proceeding
- Single source of truth for migrations status
Added version-based migration that automatically includes scene directories in workspace:
- Scans …
> fix: config reset on app restart and improve migrations handling

- packages/main/src/modules/cli.ts
The following error does not get caught by the current try/catch because the `sdk-commands start` is being run, but the `waitFor(/decentraland:\/\//i)` keeps waiting forever for the success message that never arrives.
I added the `/CliError/i` regex to catch this particular error message that contains that string. I didn't add any `/error/i` because there might be errores logged by the CLI that don't require to kill the preview.
I also added the race against the `wait()` helper, that should throw if the process exits with a non-zero code.
The logs:
```
[2025-01-29 15:43:53.663] [info]  [UtilityProcess] @dcl/sdk-commands start v7.7.1
[2025-01-29 15:43:54.540] [info]  [UtilityProcess] [1/2] Bundling file /Users/mostro/Library/Application Support/creator-hub/Scenes/New Scene/src/index.ts …
```
> fix: recover from node_modules from wrong platform error

- packages/main/src/modules/cli.ts
Removed `await` since it is being awaited by `Promise.race()`
> fix: wrong await

- packages/main/src/index.ts
- packages/main/src/modules/bin.ts
- packages/main/src/modules/cli.ts
- packages/main/src/modules/ipc.ts
- packages/preload/src/modules/editor.ts
- packages/preload/src/modules/workspace.ts
- packages/renderer/src/components/EditorPage/component.tsx
- packages/renderer/src/hooks/useEditor.ts
- packages/renderer/src/modules/store/editor/slice.ts
- packages/shared/types/ipc.ts
also error handling when importing scene and its not accesible
> feat: handle multiple previews at the same time

- package-lock.json
- package.json
- packages/renderer/src/components/HomePage/styles.css
- packages/renderer/src/components/Modals/PublishProject/steps/Deploy/component.tsx
- packages/renderer/src/hooks/useDeploy.ts
- packages/renderer/src/modules/store/deployment/slice.spec.ts
- packages/renderer/src/modules/store/deployment/slice.ts
- packages/renderer/src/modules/store/deployment/utils.spec.ts
- packages/renderer/src/modules/store/deployment/utils.ts
- packages/renderer/src/modules/store/utils.spec.ts
- packages/renderer/src/modules/store/utils.ts
- packages/renderer/tests/setupTests.ts
- packages/renderer/tests/utils/testStore.ts
- packages/renderer/vite.config.js
- packages/shared/types/deploy.ts
This PR adds a retry mechanism to deploy scenes to an available catalyst server when one of them is unavailable.
Fixes: https://github.com/decentraland/creator-hub/issues/491
> fix: Deploy to available catalyst server

- .gitignore
- packages/preload/src/modules/workspace.ts
- packages/preload/tests/modules/workspace.spec.ts
- packages/renderer/src/components/Modals/CreateProject/component.tsx
- packages/renderer/src/components/TemplatesPage/component.tsx
- packages/renderer/src/hooks/useWorkspace.ts
- packages/renderer/src/modules/store/translation/locales/en.json
- packages/renderer/src/modules/store/translation/locales/es.json
- packages/renderer/src/modules/store/translation/locales/zh.json
closes https://github.com/decentraland/creator-hub/issues/544
> update CreateProject to split name and path

- packages/renderer/src/components/ExpandMore/component.tsx
- packages/renderer/src/components/ExpandMore/index.ts
- packages/renderer/src/components/ExpandMore/styles.css
- packages/renderer/src/components/ExpandMore/types.ts
- packages/renderer/src/components/Modals/PublishProject/steps/Deploy/component.tsx
- packages/renderer/src/components/Modals/PublishProject/steps/Deploy/styles.css
- packages/renderer/src/components/Modals/PublishProject/steps/PublishToLand/component.tsx
- packages/renderer/src/hooks/useDeploy.ts
- packages/renderer/src/hooks/useEditor.ts
- packages/renderer/src/modules/store/deployment/slice.spec.ts
- packages/renderer/src/modules/store/deployment/slice.ts
- packages/renderer/src/modules/store/deployment/utils.ts
- packages/renderer/src/modules/store/editor/slice.ts
- packages/renderer/src/modules/store/translation/locales/en.json
- packages/renderer/src/modules/store/translation/locales/es.json
- packages/renderer/src/modules/store/translation/locales/zh.json
- packages/shared/types/deploy.ts
closes https://github.com/decentraland/creator-hub/issues/511
> feat: Deploy errors

- package-lock.json
- package.json
- packages/main/src/index.ts
- packages/main/src/modules/cli.ts
- packages/main/src/modules/handle.ts
- packages/preload/src/modules/editor.ts
- packages/preload/src/services/ipc.ts
- packages/renderer/src/components/Modals/PublishProject/steps/Deploy/component.tsx
- packages/renderer/src/components/TemplatesPage/component.tsx
- packages/renderer/src/components/TranslationProvider/utils.ts
- packages/renderer/src/hooks/useEditor.ts
- packages/renderer/src/modules/store/deployment/slice.ts
- packages/renderer/src/modules/store/editor/slice.ts
- packages/renderer/src/modules/store/translation/slice.ts
- packages/renderer/src/modules/store/translation/types.ts
- packages/renderer/src/modules/store/translation/utils.ts
- packages/shared/try-catch.ts
- packages/shared/types/deploy.ts
- packages/shared/types/ipc.ts
- packages/shared/types/translation.ts
requires: https://github.com/decentraland/js-sdk-toolchain/pull/1144
This PR introduces significant improvements to the deployment system, including programmatic deployment mode, enhanced error handling with structured error information, and better integration between the main process and SDK commands.
- **Added programmatic deployment support** that directly integrates with SDK commands instead of spawning child processes
- **Implemented legacy deployment detection** to maintain backward compatibility with older SDK versions
- **Enhanced deployment server management** with proper cleanup and stop functionality
- **Improved deployment flow** with better error propagation and user feedback
None - this is a backward-compatible enhancement that maintains all existing functionality while …
> feat: call sdk-commands programatically 

- .github/workflows/release.yml
- electron-builder.cjs
This PR updates the `files` and `asarUnpack` patterns to align with the latest changes in electron-builder.
Recent updates to electron-builder modified how these patterns are interpreted, causing some required dependencies to be excluded from the final build. 
These dependencies are necessary for installing scene-related packages at runtime.
> fix: unpackaging npm dependencies

- package-lock.json
- package.json
This PR upgrades the `@sdk/inspector` package to fix a loading model issue.
Depends on: https://github.com/decentraland/js-sdk-toolchain/pull/1173
Test cases:
> fix: Upgrade inspector package

- packages/inspector/src/lib/sdk/operations/remove-entity.ts
Whenever an item is deleted, this closes the right-side panel with the item properties. The problem is that the canvas changes size and the center of the screen shifts in an abrupt way, this motion is very distracting and doesn't feel good.
This PR solves this issue by selecting the parent element of the removed entity to keep the right-side panel.
- Remove a selected item on the root
- Remove a selected item that has a parent node
- Remove the parent of a selected item
> Fix: canvas resize on delete entity

- README.md
Added a note how to avoid the "image damaged" error on MacOS when testing PR builds
> chore: readme launch locally

- .github/pull_request_template.md
It's bothersome to write your PR description from scratch every time and we don't have an standard.
Added a cool PR template to the repo 🚀
> Chore: Add pull request template

- .github/actions/update-release-description/action.yml
- packages/inspector/README.md
Fixed YAML parsing error in the `update-release-description` action by passing release notes through an environment
variable instead of using heredoc syntax.
The action was failing with a YAML parsing error:
Error: (Line: 63, Col: 1, Idx: 2185) - While scanning a simple key, could not find expected ':''.
The heredoc delimiter `EOF` at column 0 was confusing the YAML parser, which interpreted it as a YAML key without a
value. Additionally, using `echo` or direct variable assignment broke when release notes contained apostrophes in
commit messages.
- Pass `release_notes` input as an environment variable (`RELEASE_NOTES`)
- Use `printf '%s' "$RELEASE_NOTES"` to write the content to a temporary file
- This approach safely handles all special characters (quotes, apostrophes, newlines) without …
> fix: release description action
